# Generated by Django 4.2.7 on 2025-09-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskassignment',
            options={'ordering': ['-assigned_at']},
        ),
    ]
